### ISSUE TITLE
Elastic search connection error on ./scripts/setup

### ISSUE THREAD

**Issue by nishadhka** [inveniosoftware/cookiecutter-invenio-instance#76]
Following the instruction in [here](https://github.com/inveniosoftware/invenio/blob/master/docs/quickstart/quickstart.rst), after completing all the prior steps without any error. the step ```./scripts/setup```, ends in following error
```
Cache cleared
Destroying database postgresql+psycopg2://uebibrepo:uebibrepo@localhost/uebibrepo
Creating database postgresql+psycopg2://uebibrepo:uebibrepo@localhost/uebibrepo
Creating all tables!
  [####################################]  100%             
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Created all tables!
Traceback (most recent call last):
  File "/usr/local/bin/invenio", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invenio_search/cli.py", line 34, in inner
    cluster_ver = current_search.cluster_version[0]
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/invenio_search/ext.py", line 221, in cluster_version
    versionstr = self.client.info()['version']['number']
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 241, in info
    return self.transport.perform_request('GET', '/', params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 85, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))
```
the comment was executed both virtualenv enabled as of ```pipenv install -e ./my-datamodel``` its output message saying to run ```pipenv shell``` and without virtualenv, both ends up in same above error. Requesting help in relsoving this error.

**Comment by remram44** [comment]
I'm guessing the 'es' container is loop-crashing, did you forget [this step](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode)?

**Comment by nishadhka** [comment]
Thank you, will try and note here

**Comment by nishadhka** [comment]
@remram44 it solved the error, thank you
